# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'EJRxSwiftTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EJRxSwiftTest

   pod 'RxSwift', '~> 4.3.1'

end
