# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HowlTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HowlTalk

    pod 'Firebase/Database'
	pod 'Firebase/Auth'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Analytics'
    pod 'SnapKit', '~> 5.0.0'
    pod 'TextFieldEffects'
	pod 'Firebase/Storage'
end
